export const data = {
  email: "tony.peter@carisma-solutions.com.au",
  user_id: 1,
  first_name: "Tony",
  middle_name: null,
  last_name: "Fernandas",
  role: "admin",
  role_id: 26,
  company_id: 1,
  project_id: 0,
  portal_id: 2,
  dashboards: "0,3,5",
  company_logo:
    "https://www.carisma-solutions.com.au/assets/img/icons/CS%20logo.png",
  company_name: "Carisma Solutions Private Ltd",
  staff_id: 927,
  master_company: {
    id: 1,
    name: "Carisma Solutions",
    short_name: "CS",
    description: null,
    logo: "https://www.carisma-solutions.com.au/Images/logo.svg",
    fallback_logo: "/assets/brand/carsimasolutions_christmas.png",
    primary_color: "#811331",
    primary_color_rgb: "129, 19, 49",
    secondary_color: "",
    portal_link: "https://clientportal.carisma-solutions.com.au/login",
    support_email: "clientportalsupport@carisma-solutions.com.au",
    created_by: null,
    created_at: "2023-12-19T15:34:42.000000Z",
    updated_by: null,
    updated_at: null,
  },
  test_dashboards: "0,3,5",
  app: {
    portal: 1,
    sub_portal: 1,
    version: "1.5",
    latest_version: "1.5",
    latest_version_id: 4,
    latest_update: {
      title: "Winter Update 1.5 released!",
      notes:
        "<p>Portal has been updated with new features that helps you track jobs and communicate more efficient.\n<p>\n<ul>\n    <li>Instructions has been added to Job Status for more enhanced communication.</li>\n    <li>Now you can upload your own photo to your profile.</li>\n    <li>New feedback tab added in Dashboard for you to send feedback that will help us provide better service.</li>\n</ul>",
    },
    local: {
      major_version: 1,
      minor_version: 5,
    },
  },
};
