export const jobTableHeaders = [
  { id: 'jobName', label: 'Job Name' },
  { id: 'location', label: 'Location' },
  { id: 'jobType', label: 'Job Type' },
  { id: 'receivedFrom', label: 'Received From' },
  { id: 'partner', label: 'Partner' },
  { id: 'accountant', label: 'Accountant' },
  { id: 'status', label: 'Status' },
  { id: 'receivedDate', label: 'Received Date' },
  { id: 'commencedDate', label: 'Commenced Date' },
  { id: 'querySentDate', label: 'Query Sent Date' },
  { id: 'queryRepliesReceivedDate', label: 'Query Replies Recieved Dated' },
  { id: 'internalReviewSentDate', label: 'Internal Review Sent Date' },
  { id: 'reviewSentDate', label: 'Review Sent Date' },
  { id: 'reviewRepliesReceivedDate', label: 'Review Replies Received Date' },
  { id: 'finalReviewSentDate', label: 'Final Review Sent Date' },
  { id: 'closedDate', label: 'Closed Date' },
  { id: 'timeTakenTillDate', label: 'Time Taken Till Date' },
  { id: 'underOrOverBudget', label: 'Under / (Over) Budget' },
  { id: 'amount', label: 'Amount ($)' },
  { id: 'hours', label: 'Hours' },
  { id: 'priorityDate', label: 'Priority Date' },
  { id: 'budgetAlertDate', label: 'Budget Alert Date' },
  { id: 'remarks', label: 'Remarks' }
];